name: Unit Tests

on: [push, pull_request]

jobs:
  build-and-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci && npm ci --prefix cli
      - run: npm run bundle
      - run: npm test
